name: pubish docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        run: nix build -L .#dockerImage

      - name: log in to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish docker image
        run: |
          docker load < result
          docker tag lurker:latest ghcr.io/${{ github.repository_owner }}/lurker:latest
          docker push ghcr.io/${{ github.repository_owner }}/lurker:latest
